export const ELEMENT_NODE = 1; //	An Element node like <p> or <div>.
export const ATTRIBUTE_NODE = 2; //	An Attribute of an Element.
export const TEXT_NODE = 3; //	The actual Text inside an Element or Attr.
export const CDATA_SECTION_NODE = 4; //	A CDATASection, such as <!CDATA[[ … ]]>.
export const PROCESSING_INSTRUCTION_NODE = 7; //	A ProcessingInstruction of an XML document, such as <?xml-stylesheet … ?>.
export const COMMENT_NODE = 8; //	A Comment node, such as <!-- … -->.
export const DOCUMENT_NODE = 9; //	A Document node.
export const DOCUMENT_TYPE_NODE = 10; //	A DocumentType node, such as <!DOCTYPE html>.
export const DOCUMENT_FRAGMENT_NODE = 11; //	A DocumentFragment node.
